
// This file has been generated by the GUI designer. Do not modify.

public partial class MainWindow
{
	private global::Gtk.Frame frame1;
	
	private global::Gtk.VBox vbox3;
	
	private global::Gtk.HBox hbox2;
	
	private global::Gtk.Entry entry4;
	
	private global::Gtk.ToggleButton togglebutton1;
	
	private global::Gtk.HBox hbox4;
	
	private global::Gtk.Alignment alignment2;
	
	private global::Gtk.Alignment alignment3;
	
	private global::Gtk.Label label1;
	
	private global::Gtk.ComboBox combobox1;
	
	private global::Gtk.Label label2;
	
	private global::Gtk.ColorButton colorbutton1;
	
	private global::Gtk.Label GtkLabel1;

	protected virtual void Build ()
	{
		global::Stetic.Gui.Initialize (this);
		// Widget MainWindow
		this.Name = "MainWindow";
		this.Title = global::Mono.Unix.Catalog.GetString ("unicast");
		this.WindowPosition = ((global::Gtk.WindowPosition)(4));
		// Container child MainWindow.Gtk.Container+ContainerChild
		this.frame1 = new global::Gtk.Frame ();
		this.frame1.Name = "frame1";
		this.frame1.ShadowType = ((global::Gtk.ShadowType)(0));
		// Container child frame1.Gtk.Container+ContainerChild
		this.vbox3 = new global::Gtk.VBox ();
		this.vbox3.Name = "vbox3";
		this.vbox3.Spacing = 6;
		// Container child vbox3.Gtk.Box+BoxChild
		this.hbox2 = new global::Gtk.HBox ();
		this.hbox2.Name = "hbox2";
		this.hbox2.Spacing = 6;
		// Container child hbox2.Gtk.Box+BoxChild
		this.entry4 = new global::Gtk.Entry ();
		this.entry4.CanFocus = true;
		this.entry4.Name = "entry4";
		this.entry4.IsEditable = true;
		this.entry4.InvisibleChar = '•';
		this.hbox2.Add (this.entry4);
		global::Gtk.Box.BoxChild w1 = ((global::Gtk.Box.BoxChild)(this.hbox2 [this.entry4]));
		w1.Position = 0;
		// Container child hbox2.Gtk.Box+BoxChild
		this.togglebutton1 = new global::Gtk.ToggleButton ();
		this.togglebutton1.CanFocus = true;
		this.togglebutton1.Name = "togglebutton1";
		this.togglebutton1.UseUnderline = true;
		this.togglebutton1.Label = global::Mono.Unix.Catalog.GetString ("Start");
		this.hbox2.Add (this.togglebutton1);
		global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.hbox2 [this.togglebutton1]));
		w2.Position = 1;
		w2.Expand = false;
		w2.Fill = false;
		this.vbox3.Add (this.hbox2);
		global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.vbox3 [this.hbox2]));
		w3.Position = 0;
		w3.Expand = false;
		w3.Fill = false;
		// Container child vbox3.Gtk.Box+BoxChild
		this.hbox4 = new global::Gtk.HBox ();
		this.hbox4.Name = "hbox4";
		this.hbox4.Spacing = 6;
		// Container child hbox4.Gtk.Box+BoxChild
		this.alignment2 = new global::Gtk.Alignment (0.5F, 0.5F, 1F, 1F);
		this.alignment2.Name = "alignment2";
		// Container child alignment2.Gtk.Container+ContainerChild
		this.alignment3 = new global::Gtk.Alignment (0.5F, 0.5F, 1F, 1F);
		this.alignment3.Name = "alignment3";
		// Container child alignment3.Gtk.Container+ContainerChild
		this.label1 = new global::Gtk.Label ();
		this.label1.Name = "label1";
		this.label1.LabelProp = "reload time (sec)";
		this.alignment3.Add (this.label1);
		this.alignment2.Add (this.alignment3);
		this.hbox4.Add (this.alignment2);
		global::Gtk.Box.BoxChild w6 = ((global::Gtk.Box.BoxChild)(this.hbox4 [this.alignment2]));
		w6.Position = 0;
		w6.Expand = false;
		w6.Fill = false;
		// Container child hbox4.Gtk.Box+BoxChild
		this.combobox1 = global::Gtk.ComboBox.NewText ();
		this.combobox1.AppendText (global::Mono.Unix.Catalog.GetString ("10"));
		this.combobox1.AppendText (global::Mono.Unix.Catalog.GetString ("20"));
		this.combobox1.AppendText (global::Mono.Unix.Catalog.GetString ("30"));
		this.combobox1.AppendText (global::Mono.Unix.Catalog.GetString ("45"));
		this.combobox1.AppendText (global::Mono.Unix.Catalog.GetString ("60"));
		this.combobox1.Name = "combobox1";
		this.combobox1.Active = 2;
		this.hbox4.Add (this.combobox1);
		global::Gtk.Box.BoxChild w7 = ((global::Gtk.Box.BoxChild)(this.hbox4 [this.combobox1]));
		w7.Position = 1;
		w7.Expand = false;
		w7.Fill = false;
		// Container child hbox4.Gtk.Box+BoxChild
		this.label2 = new global::Gtk.Label ();
		this.label2.Name = "label2";
		this.label2.LabelProp = global::Mono.Unix.Catalog.GetString ("text color");
		this.hbox4.Add (this.label2);
		global::Gtk.Box.BoxChild w8 = ((global::Gtk.Box.BoxChild)(this.hbox4 [this.label2]));
		w8.Position = 2;
		w8.Expand = false;
		w8.Fill = false;
		// Container child hbox4.Gtk.Box+BoxChild
		this.colorbutton1 = new global::Gtk.ColorButton ();
		this.colorbutton1.CanFocus = true;
		this.colorbutton1.Events = ((global::Gdk.EventMask)(784));
		this.colorbutton1.Name = "colorbutton1";
		this.hbox4.Add (this.colorbutton1);
		global::Gtk.Box.BoxChild w9 = ((global::Gtk.Box.BoxChild)(this.hbox4 [this.colorbutton1]));
		w9.Position = 3;
		w9.Expand = false;
		w9.Fill = false;
		this.vbox3.Add (this.hbox4);
		global::Gtk.Box.BoxChild w10 = ((global::Gtk.Box.BoxChild)(this.vbox3 [this.hbox4]));
		w10.Position = 1;
		w10.Expand = false;
		w10.Fill = false;
		this.frame1.Add (this.vbox3);
		this.GtkLabel1 = new global::Gtk.Label ();
		this.GtkLabel1.Name = "GtkLabel1";
		this.GtkLabel1.Ypad = 10;
		this.GtkLabel1.LabelProp = global::Mono.Unix.Catalog.GetString ("<b>Shitaraba</b>");
		this.GtkLabel1.UseMarkup = true;
		this.frame1.LabelWidget = this.GtkLabel1;
		this.Add (this.frame1);
		if ((this.Child != null)) {
			this.Child.ShowAll ();
		}
		this.DefaultWidth = 566;
		this.DefaultHeight = 98;
		this.Show ();
		this.DeleteEvent += new global::Gtk.DeleteEventHandler (this.OnDeleteEvent);
		this.togglebutton1.Clicked += new global::System.EventHandler (this.OnToggleClicked);
		this.combobox1.Changed += new global::System.EventHandler (this.OnReloadTimeChanged);
		this.colorbutton1.ColorSet += new global::System.EventHandler (this.OnColorChange);
	}
}
